name: mocodad
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - anyio=3.7.1=pyhd8ed1ab_0
  - arrow=1.2.3=pyhd8ed1ab_0
  - attrs=23.1.0=pyh71513ae_1
  - backoff=2.2.1=pyhd8ed1ab_0
  - backports=1.0=pyhd8ed1ab_3
  - backports.functools_lru_cache=1.6.5=pyhd8ed1ab_0
  - beautifulsoup4=4.12.2=pyha770c72_0
  - blas=1.0=mkl
  - blessed=1.19.1=pyhe4f9e05_2
  - brotli=1.0.9=h5eee18b_7
  - brotli-bin=1.0.9=h5eee18b_7
  - brotlipy=0.7.0=py311h5eee18b_1002
  - bzip2=1.0.8=h7b6447c_0
  - ca-certificates=2023.05.30=h06a4308_0
  - cachecontrol=0.12.11=py311h06a4308_1
  - certifi=2023.7.22=py311h06a4308_0
  - cffi=1.15.1=py311h5eee18b_3
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - cleo=2.0.1=pyhd8ed1ab_0
  - click=8.1.6=unix_pyh707e725_0
  - colorama=0.4.6=pyhd8ed1ab_0
  - contourpy=1.0.5=py311hdb19cb5_0
  - crashtest=0.4.1=pyhd8ed1ab_0
  - croniter=1.4.1=pyhd8ed1ab_0
  - cryptography=41.0.2=py311h22a60cf_0
  - cuda-cudart=11.8.89=0
  - cuda-cupti=11.8.87=0
  - cuda-libraries=11.8.0=0
  - cuda-nvrtc=11.8.89=0
  - cuda-nvtx=11.8.86=0
  - cuda-runtime=11.8.0=0
  - cycler=0.11.0=pyhd3eb1b0_0
  - dateutils=0.6.12=py_0
  - dbus=1.13.18=hb2f20db_0
  - deepdiff=5.8.1=pyhd8ed1ab_0
  - distlib=0.3.7=pyhd8ed1ab_0
  - dulwich=0.21.3=py311h5eee18b_0
  - exceptiongroup=1.1.2=pyhd8ed1ab_0
  - expat=2.2.10=h9c3ff4c_0
  - fastapi=0.100.1=pyhd8ed1ab_0
  - ffmpeg=4.3=hf484d3e_0
  - filelock=3.9.0=py311h06a4308_0
  - fontconfig=2.14.1=hef1e5e3_0
  - fonttools=4.25.0=pyhd3eb1b0_0
  - freetype=2.12.1=h4a9f257_0
  - fsspec=2023.6.0=pyh1a96a4e_0
  - giflib=5.2.1=h5eee18b_3
  - glib=2.69.1=he621ea3_2
  - gmp=6.2.1=h295c915_3
  - gmpy2=2.1.2=py311hc9b5ff0_0
  - gnutls=3.6.15=he1e5248_0
  - gst-plugins-base=1.14.1=h6a678d5_1
  - gstreamer=1.14.1=h5eee18b_1
  - h11=0.14.0=pyhd8ed1ab_0
  - html5lib=1.1=pyh9f0ad1d_0
  - icu=58.2=he6710b0_3
  - idna=3.4=py311h06a4308_0
  - importlib-metadata=6.8.0=pyha770c72_0
  - importlib_metadata=6.8.0=hd8ed1ab_0
  - importlib_resources=6.0.0=pyhd8ed1ab_1
  - inquirer=3.1.3=pyhd8ed1ab_0
  - intel-openmp=2023.1.0=hdb19cb5_46305
  - itsdangerous=2.1.2=pyhd8ed1ab_0
  - jaraco.classes=3.3.0=pyhd8ed1ab_0
  - jeepney=0.8.0=pyhd8ed1ab_0
  - jinja2=3.1.2=py311h06a4308_0
  - jpeg=9e=h5eee18b_1
  - jsonschema=4.17.3=pyhd8ed1ab_0
  - keyring=23.13.1=py311h38be061_0
  - kiwisolver=1.4.4=py311h6a678d5_0
  - krb5=1.20.1=h143b758_1
  - lame=3.100=h7b6447c_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.38=h1181459_1
  - lerc=3.0=h295c915_0
  - libbrotlicommon=1.0.9=h5eee18b_7
  - libbrotlidec=1.0.9=h5eee18b_7
  - libbrotlienc=1.0.9=h5eee18b_7
  - libclang=10.0.1=default_hb85057a_2
  - libcublas=11.11.3.6=0
  - libcufft=10.9.0.58=0
  - libcufile=1.7.1.12=0
  - libcurand=10.3.3.129=0
  - libcusolver=11.4.1.48=0
  - libcusparse=11.7.5.86=0
  - libdeflate=1.17=h5eee18b_0
  - libedit=3.1.20221030=h5eee18b_0
  - libevent=2.1.12=hdbd6064_1
  - libffi=3.4.4=h6a678d5_0
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libiconv=1.16=h7f8727e_2
  - libidn2=2.3.4=h5eee18b_0
  - libllvm10=10.0.1=hbcb73fb_5
  - libnpp=11.8.0.86=0
  - libnvjpeg=11.9.0.86=0
  - libpng=1.6.39=h5eee18b_0
  - libpq=12.15=hdbd6064_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtasn1=4.19.0=h5eee18b_0
  - libtiff=4.5.0=h6a678d5_2
  - libunistring=0.9.10=h27cfd23_0
  - libuuid=1.41.5=h5eee18b_0
  - libwebp=1.2.4=h11a3e52_1
  - libwebp-base=1.2.4=h5eee18b_1
  - libxcb=1.15=h7f8727e_0
  - libxkbcommon=1.0.1=hfa300c1_0
  - libxml2=2.9.14=h74e7548_0
  - libxslt=1.1.35=h4e12654_0
  - lightning=2.0.6=pyhd8ed1ab_0
  - lightning-cloud=0.5.37=pyhd8ed1ab_0
  - lightning-utilities=0.9.0=pyhd8ed1ab_0
  - lockfile=0.12.2=py_1
  - lz4-c=1.9.4=h6a678d5_0
  - markdown-it-py=3.0.0=pyhd8ed1ab_0
  - markupsafe=2.1.1=py311h5eee18b_0
  - matplotlib=3.7.1=py311h06a4308_1
  - matplotlib-base=3.7.1=py311ha02d727_1
  - mdurl=0.1.0=pyhd8ed1ab_0
  - mkl=2023.1.0=h6d00ec8_46342
  - mkl-service=2.4.0=py311h5eee18b_1
  - mkl_fft=1.3.6=py311ha02d727_1
  - mkl_random=1.2.2=py311ha02d727_1
  - more-itertools=10.0.0=pyhd8ed1ab_1
  - mpc=1.1.0=h10f8cd9_1
  - mpfr=4.0.2=hb69a4c5_1
  - mpmath=1.2.1=py311h06a4308_0
  - msgpack-python=1.0.3=py311hdb19cb5_0
  - munkres=1.1.4=py_0
  - ncurses=6.4=h6a678d5_0
  - nettle=3.7.3=hbbd107a_1
  - networkx=3.1=py311h06a4308_0
  - nspr=4.35=h6a678d5_0
  - nss=3.89.1=h6a678d5_0
  - numpy-base=1.25.0=py311hf175353_0
  - openh264=2.1.1=h4ff587b_0
  - openssl=3.0.9=h7f8727e_0
  - ordered-set=4.1.0=pyhd8ed1ab_0
  - packaging=23.1=pyhd8ed1ab_0
  - pcre=8.45=h9c3ff4c_0
  - pexpect=4.8.0=pyh1a96a4e_2
  - pillow=9.4.0=py311h6a678d5_0
  - pip=23.2.1=py311h06a4308_0
  - pkginfo=1.9.6=pyhd8ed1ab_0
  - pkgutil-resolve-name=1.3.10=pyhd8ed1ab_0
  - platformdirs=2.5.2=py311h06a4308_0
  - ply=3.11=py311h06a4308_0
  - poetry=1.4.0=py311h06a4308_0
  - poetry-core=1.5.1=py311h06a4308_0
  - poetry-plugin-export=1.3.0=py311h4849bfd_0
  - psutil=5.9.0=py311h5eee18b_0
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pydantic=1.10.8=py311h5eee18b_0
  - pygments=2.15.1=pyhd8ed1ab_0
  - pyjwt=2.8.0=pyhd8ed1ab_0
  - pyopenssl=23.2.0=py311h06a4308_0
  - pyparsing=3.0.9=py311h06a4308_0
  - pyproject_hooks=1.0.0=pyhd8ed1ab_0
  - pyqt=5.15.7=py311h6a678d5_0
  - pyqt5-sip=12.11.0=py311h6a678d5_0
  - pyrsistent=0.18.0=py311h5eee18b_0
  - pysocks=1.7.1=py311h06a4308_0
  - python=3.11.4=h955ad1f_0
  - python-build=0.10.0=pyhd8ed1ab_1
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python-editor=1.0.4=py_0
  - python-installer=0.6.0=py311h06a4308_0
  - python-multipart=0.0.6=pyhd8ed1ab_0
  - python_abi=3.11=2_cp311
  - pytorch=2.0.1=py3.11_cuda11.8_cudnn8.7.0_0
  - pytorch-cuda=11.8=h7e8668a_5
  - pytorch-lightning=2.0.6=pyhd8ed1ab_0
  - pytorch-mutex=1.0=cuda
  - pytz=2023.3=pyhd8ed1ab_0
  - pyyaml=6.0=py311h5eee18b_1
  - qt-main=5.15.2=h327a75a_7
  - qt-webengine=5.15.9=hd2b0992_4
  - qtwebkit=5.212=h4eab89a_4
  - rapidfuzz=2.13.7=py311ha02d727_0
  - readchar=4.0.5=pyhd8ed1ab_0
  - readline=8.2=h5eee18b_0
  - requests=2.31.0=py311h06a4308_0
  - requests-toolbelt=0.10.1=pyhd8ed1ab_0
  - rich=13.5.1=pyhd8ed1ab_0
  - secretstorage=3.3.3=py311h38be061_1
  - setuptools=68.0.0=py311h06a4308_0
  - shellingham=1.5.1=pyhd8ed1ab_0
  - sip=6.6.2=py311h6a678d5_0
  - six=1.16.0=pyh6c4a22f_0
  - sniffio=1.3.0=pyhd8ed1ab_0
  - soupsieve=2.3.2.post1=pyhd8ed1ab_0
  - sqlite=3.41.2=h5eee18b_0
  - starlette=0.27.0=pyhd8ed1ab_0
  - starsessions=1.3.0=pyhd8ed1ab_0
  - sympy=1.11.1=py311h06a4308_0
  - tbb=2021.8.0=hdb19cb5_0
  - tk=8.6.12=h1ccaba5_0
  - toml=0.10.2=pyhd3eb1b0_0
  - tomli=2.0.1=pyhd8ed1ab_0
  - tomlkit=0.12.1=pyha770c72_0
  - torchaudio=2.0.2=py311_cu118
  - torchmetrics=0.11.4=pyhd8ed1ab_0
  - torchtriton=2.0.0=py311
  - torchvision=0.15.2=py311_cu118
  - tornado=6.2=py311h5eee18b_0
  - tqdm=4.65.0=pyhd8ed1ab_1
  - traitlets=5.9.0=pyhd8ed1ab_0
  - trove-classifiers=2023.7.6=pyhd8ed1ab_0
  - typing-extensions=4.7.1=py311h06a4308_0
  - typing_extensions=4.7.1=py311h06a4308_0
  - tzdata=2023c=h04d1e81_0
  - urllib3=1.26.16=py311h06a4308_0
  - uvicorn=0.23.2=py311h38be061_0
  - virtualenv=20.17.1=py311h38be061_0
  - wcwidth=0.2.6=pyhd8ed1ab_0
  - webencodings=0.5.1=py_1
  - websocket-client=1.6.1=pyhd8ed1ab_0
  - websockets=10.4=py311h5eee18b_1
  - wheel=0.38.4=py311h06a4308_0
  - xz=5.4.2=h5eee18b_0
  - yaml=0.2.5=h7f98852_2
  - zipp=3.16.2=pyhd8ed1ab_0
  - zlib=1.2.13=h5eee18b_0
  - zstd=1.5.5=hc292b87_0
  - pip:
      - appdirs==1.4.4
      - docker-pycreds==0.4.0
      - gitdb==4.0.10
      - gitpython==3.1.32
      - joblib==1.3.1
      - numpy==1.25.2
      - pathtools==0.1.2
      - protobuf==4.23.4
      - scikit-learn==1.3.0
      - scipy==1.11.1
      - sentry-sdk==1.29.2
      - setproctitle==1.3.2
      - smmap==5.0.0
      - threadpoolctl==3.2.0
      - wandb==0.15.8
prefix: /home/odin/miniconda3/envs/mocodad
