name: mocodad
channels:
  - pytorch
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - _tflow_select=2.3.0
  - absl-py=1.0.0
  - aiohttp=3.8.1
  - aiosignal=1.2.0
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - astor=0.8.1
  - asttokens=2.0.5
  - astunparse=1.6.3
  - async-timeout=4.0.2
  - attrs=21.4.0
  - backcall=0.2.0
  - beautifulsoup4=4.11.1
  - blas=1.0
  - bleach=4.1.0
  - blinker=1.4
  - bottleneck=1.3.4
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.18.1
  - ca-certificates=2022.12.7
  - cachetools=5.0.0
  - certifi=2022.12.7
  - cffi=1.15.0
  - charset-normalizer=2.0.4
  - click=8.1.3
  - colorama=0.4.4
  - cryptography=36.0.0
  - cudatoolkit=11.3.1
  - cycler=0.11.0
  - dbus=1.13.18
  - debugpy=1.5.1
  - decorator=5.1.1
  - defusedxml=0.7.1
  - docker-pycreds=0.4.0
  - entrypoints=0.4
  - et_xmlfile=1.1.0
  - executing=0.8.3
  - expat=2.4.4
  - ffmpeg=4.3
  - fontconfig=2.13.1
  - fonttools=4.25.0
  - freetype=2.11.0
  - frozenlist=1.2.0
  - fsspec=2022.5.0
  - future=0.18.2
  - gast=0.4.0
  - giflib=5.2.1
  - gitdb=4.0.7
  - gitpython=3.1.27
  - glib=2.69.1
  - gmp=6.2.1
  - gnutls=3.6.15
  - google-auth=2.6.6
  - google-auth-oauthlib=0.4.6
  - google-pasta=0.2.0
  - grpcio=1.42.0
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - h5py=2.10.0
  - hdf5=1.10.6
  - icu=58.2
  - idna=3.3
  - importlib-metadata=4.11.3
  - intel-openmp=2021.4.0
  - ipykernel=6.9.1
  - ipython=8.4.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.6.5
  - jedi=0.18.1
  - jinja2=3.0.3
  - jpeg=9d
  - jsonschema=4.4.0
  - jupyter=1.0.0
  - jupyter_client=7.2.2
  - jupyter_console=6.4.3
  - jupyter_core=4.10.0
  - jupyterlab_pygments=0.1.2
  - jupyterlab_widgets=1.0.0
  - keras=2.4.3
  - keras-preprocessing=1.1.2
  - kiwisolver=1.3.2
  - kneed=0.7.0
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.35.1
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libffi=3.3
  - libgcc-ng=9.3.0
  - libgfortran-ng=7.5.0
  - libgfortran4=7.5.0
  - libgomp=9.3.0
  - libiconv=1.15
  - libidn2=2.3.2
  - libpng=1.6.37
  - libprotobuf=3.19.1
  - libsodium=1.0.18
  - libstdcxx-ng=9.3.0
  - libtasn1=4.16.0
  - libtiff=4.2.0
  - libunistring=0.9.10
  - libuuid=1.0.3
  - libuv=1.40.0
  - libwebp=1.2.2
  - libwebp-base=1.2.2
  - libxcb=1.15
  - libxml2=2.9.12
  - lz4-c=1.9.3
  - markdown=3.3.7
  - markupsafe=2.1.1
  - matplotlib=3.5.1
  - matplotlib-base=3.5.1
  - matplotlib-inline=0.1.2
  - mistune=0.8.4
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - multidict=5.2.0
  - munkres=1.1.4
  - nbclient=0.5.13
  - nbconvert=6.4.4
  - nbformat=5.3.0
  - ncurses=6.3
  - nest-asyncio=1.5.5
  - nettle=3.7.3
  - notebook=6.4.11
  - numexpr=2.8.1
  - oauthlib=3.2.0
  - openh264=2.1.1
  - openpyxl=3.0.9
  - openssl=1.1.1t
  - opt_einsum=3.3.0
  - packaging=21.3
  - pandas=1.4.2
  - pandocfilters=1.5.0
  - parso=0.8.3
  - pathtools=0.1.2
  - pcre=8.45
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=9.0.1
  - prometheus_client=0.13.1
  - promise=2.3
  - prompt-toolkit=3.0.20
  - prompt_toolkit=3.0.20
  - protobuf=3.19.1
  - psutil=5.8.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.8
  - pycparser=2.21
  - pydeprecate=0.3.2
  - pygments=2.11.2
  - pyjwt=2.4.0
  - pyopenssl=22.0.0
  - pyparsing=3.0.9
  - pyqt=5.9.2
  - pyrsistent=0.18.0
  - pysocks=1.7.1
  - python=3.9.11
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.15.1
  - python-flatbuffers=2.0
  - python_abi=3.9
  - pytorch=1.11.0
  - pytorch-lightning=1.6.3
  - pytorch-mutex=1.0
  - pytz=2022.1
  - pyu2f=0.1.5
  - pyyaml=6.0
  - pyzmq=22.3.0
  - qt=5.9.7
  - qtconsole=5.3.1
  - qtpy=2.0.1
  - readline=8.1.2
  - requests=2.27.1
  - requests-oauthlib=1.3.1
  - rsa=4.8
  - send2trash=1.8.0
  - sentry-sdk=1.5.12
  - setproctitle=1.2.2
  - setuptools=58.0.4
  - shortuuid=1.0.8
  - sip=4.19.13
  - six=1.16.0
  - smmap=5.0.0
  - soupsieve=2.3.1
  - sqlite=3.38.2
  - stack_data=0.2.0
  - tensorboard=2.9.0
  - tensorboard-data-server=0.6.0
  - tensorboard-plugin-wit=1.8.1
  - tensorflow=2.4.1
  - tensorflow-base=2.4.1
  - tensorflow-estimator=2.6.0
  - termcolor=1.1.0
  - terminado=0.13.1
  - testpath=0.6.0
  - threadpoolctl=3.1.0
  - tk=8.6.11
  - torchaudio=0.11.0
  - torchmetrics=0.8.2
  - torchvision=0.12.0
  - tornado=6.1
  - tqdm=4.64.0
  - traitlets=5.1.1
  - typing-extensions=4.1.1
  - typing_extensions=4.1.1
  - tzdata=2022a
  - urllib3=1.26.8
  - wandb=0.12.16
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - werkzeug=2.1.2
  - wheel=0.37.1
  - widgetsnbextension=3.5.2
  - wrapt=1.13.3
  - xz=5.2.5
  - yaml=0.2.5
  - yarl=1.6.3
  - zeromq=4.3.4
  - zipp=3.8.0
  - zlib=1.2.11
  - zstd=1.4.9
  - pip:
      - blessed==1.19.1
      - copulae==0.7.7
      - cython==0.29.32
      - diptest==0.5.2
      - filelock==3.7.1
      - gdown==4.5.1
      - geoopt==0.5.0
      - gpustat==1.0.0
      - hdbscan==0.8.29
      - joblib==1.1.0
      - llvmlite==0.36.0
      - numpy==1.24.3
      - nvidia-ml-py==11.495.46
      - opencv-python==4.5.5.64
      - patsy==0.5.3
      - pip==22.2
      - scikit-learn==1.1.1
      - scipy==1.8.1
      - seaborn==0.11.2
      - statsmodels==0.14.0
      - unidip==0.1.1
